export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";

export const SET_CALENDAR_DATE = "SET_CALENDAR_DATE";
export const SET_CALENDAR_TASK = "SET_CALENDAR_TASK";

export const SAVE_TASK = "SAVE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";